# platform: linux-64
name: InductiveBiasesHarmlessInterpolation
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cudatoolkit=11.3
  - cuda-nvcc=11.3
  - cudnn=8.4
  - pytorch=1.11
  - torchvision=0.12
  - kornia=0.6
  - jupyterlab=3.4
  - ipywidgets=7.7
  - jupyterlab_widgets=1.1
  - widgetsnbextension=3.6
  - matplotlib=3.5
  - seaborn=0.11
  - numpy=1.22
  - pandas=1.4
  - scikit-learn=1.1
  - scipy=1.8
  - python-dotenv=0.20
  - black=22.3
  - tqdm=4.64
  - mlflow=1.27
  - cairo=1.16
  - pycairo=1.21
  - gin-config=0.5
  - protobuf=3.19.4  # pinned to minimize conflicts between protobuf versions
  - h5py=3.7
  - pip
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - jax[cuda11_cudnn82]==0.3.15
    - optax==0.1.3
    - flax==0.5.3
